apiVersion: v1
kind: Namespace
metadata:
  name: flagger-system
  labels:
    name: flagger-system
    app.kubernetes.io/name: flagger
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
